Lab1 1
slevinsps/techno_c_labs pull request #1
Opened 2018-10-03 11:12 UTC by slevinsps

Задача A-2. Задача о системах счисления
Time limit:	14 s
Memory limit:	64 M
Составить программу для перевода чисел из системы счисления по основанию P в систему счисления по основанию Q, где 2 меньше или равно Q меньше P меньше или равно 36. 
Значения P, Q и строковое представление S числа в исходной системе счисления вводятся с клавиатуры в следующем порядке: 
P Q S 

S не выходит за границы size_t. 

Процедура перевода не может использовать соответствующей функции системной библиотеки и должна быть оформлена в виде отдельной функции, на вход которой подаются значения P, Q и S, размещенные в динамической памяти. 
На выход функция должна возвращать строковое представление S1 числа в целевой системе счисления. 

runId 332

2018-10-03 11:52 UTC, leshiy1295 requested changes
Исправьте все замечания, после чего пришлите код на повторное ревью, указав runId новой успешной попытки в АСТС.
Постарался дублировать одинаковые замечания по всему коду - в дальнейшем для повышения эффективности нашего с Вами взаимодействия буду оставлять комментарий только при первой встрече определённого вида замечания - оставшиеся аналогичные ошибки нужно будет Вам отыскать и исправить самостоятельно

2018-10-03 11:52 UTC, leshiy1295 commented on lab1/task_a.c
> +    //assert((c <= 'Z' && c >= 'A') || (c <= 'z' && c >= 'a') || (c <= '9' && c >= '0'));
закомментированных участков кода быть не должно

2018-10-03 11:52 UTC, leshiy1295 commented on lab1/task_a.c
> +#define ASCII_NUMBER_FIRST 47
в этом нет необходимости, так как char - это целый тип, поэтому всегда можно оперировать с символами как с числами через их коды

2018-10-03 11:52 UTC, leshiy1295 commented on lab1/task_a.c
> +    return (c - 'A' + MAIN_BASE);
неясно, что такое MAIN_BASE
лучше выразить через конкретный символ

2018-10-03 11:52 UTC, leshiy1295 commented on lab1/task_a.c
> +char ret_char(int n) {
из сигнатуры не видно, что n не меняется в рамках функции

2018-10-03 11:52 UTC, leshiy1295 commented on lab1/task_a.c
> +char ret_char(int n) {
неудачное название функции - то, что она возвращает char - и так ясно из её описания

2018-10-03 11:52 UTC, leshiy1295 commented on lab1/task_a.c
> +    int len = (int)strlen(s);
что, если s будет равен NULL?

2018-10-03 11:52 UTC, leshiy1295 commented on lab1/task_a.c
> +    int len = (int)strlen(s);
неудачное название функции и, видимо, возвращаемый тип
из них непонятно, что делает функция

2018-10-03 11:52 UTC, leshiy1295 commented on lab1/task_a.c
> +    assert(p >= 2);
магическая константа

2018-10-03 11:52 UTC, leshiy1295 commented on lab1/task_a.c
> +long long int converter_to_dec(int p, char *s) {
однобуквенные идентификаторы недопустимы

2018-10-03 11:52 UTC, leshiy1295 commented on lab1/task_a.c
> +    long long int dec_ss = 0;
не рекомендуется использовать long long int
используйте либо size_t, либо явно указывайте точный тип int64_t, например, если Вам точно необходимо 64 бита. Последний вариант менее предпочтителен, поскольку в этом случае не гарантируется переносимость кода на остальные платформы

2018-10-03 11:52 UTC, leshiy1295 commented on lab1/task_a.c
> +    assert(n < MAIN_BASE && n >= 0);
assert-ы работают в DEBUG-режиме
в RELEASE они игнорируются и в случае неверных данных будет ошибка

2018-10-03 11:52 UTC, leshiy1295 commented on lab1/task_a.c
> +char *converter(int p, int q, char *s) {
непонятные названия параметров
непонятно, меняются они или нет

2018-10-03 11:52 UTC, leshiy1295 commented on lab1/task_a.c
> +    char *ans = (char *)calloc(STRING_SIZE, sizeof(char));;
что, если calloc вернёт ошибку?

2018-10-03 11:52 UTC, leshiy1295 commented on lab1/task_a.c
> +int main(void) {
main лучше разбить на отдельные функции:
- иницилизация (опционально)
- ввод
- обработка
- вывод
- освобождение ресурсов (опционально)

2018-10-03 11:52 UTC, leshiy1295 commented on lab1/task_a.c
> +int main(void) {
лучше представить программный файл в следующем виде:
- описания функций
- определение main
- определение всех остальных функций

2018-10-03 11:52 UTC, leshiy1295 commented on lab1/task_a.c
> +    int q;
все переменные необходимо инициализировать при определении

2018-10-03 11:52 UTC, leshiy1295 commented on lab1/task_a.c
> +        if (!ans)
рекомендуется всегда без исключений использовать фигурные скобки для избежания глупых ошибок в дальнейшем

2018-10-03 11:52 UTC, leshiy1295 commented on lab1/task_a.c
> +            err = ERROR_CONVERTER;
значения разных типов ошибок никак сейчас не используются => можно их не классифицировать, поскольку это явно не требуется в текущей задаче, и они никуда не выводятся

2018-10-03 11:52 UTC, leshiy1295 commented on lab1/task_a.c
> +    long long int dec_ss = converter_to_dec(p, s);
непонятное название переменной
лучше использовать другой тип

2018-10-03 11:52 UTC, leshiy1295 commented on lab1/task_a.c
> +    int err = OK;
err = OK - семантически неверная конструкция
в рассматриваемом контексте лучше заменить на result_code

2018-10-03 11:52 UTC, leshiy1295 commented on lab1/task_a.c
> +    if (scanf("%d %d %s", &p, &q, s) == 3) { // from p to q
будь названия переменных другими, комментарий не понадобился бы

2018-10-03 21:24 UTC, leshiy1295 requested changes

2018-10-03 21:24 UTC, leshiy1295 commented on lab1/task_a.c
> +# include "stdio.h"
зачем нужны отступы между # и include?

2018-10-03 21:24 UTC, leshiy1295 commented on lab1/task_a.c
> +char *converter(int p, int q, char *s);
названия переменных всё равно непонятны
то, что дано в условии - это одно
переменные в программе - это другое

2018-10-03 21:24 UTC, leshiy1295 commented on lab1/task_a.c
> +    return (symbol - 'A' + DEC_BASE);
почему здесь DEC_BASE? Из названия метода этого не следует

2018-10-03 21:24 UTC, leshiy1295 commented on lab1/task_a.c
> +char ret_symbol_from_digit(const int number) {
префикс ret не нужен
лучше уж get

2018-10-03 21:24 UTC, leshiy1295 commented on lab1/task_a.c
> +    size_t dec_ss = 0;
название переменной не поправлено

2018-10-03 21:24 UTC, leshiy1295 commented on lab1/task_a.c
> +Задача A-2. Задача о системах счисления
нужно прогнать программу через статические анализаторы (cppcheck, clang_formatter или другие, которые рассматривались на семинаре) и поправить все их замечания - в частности, ошибки по форматированию кода.

2018-10-03 21:24 UTC, leshiy1295 commented on lab1/task_a.c
> +size_t converter_to_dec(int base, char *string) {
почему string - не const?

2018-10-03 21:24 UTC, leshiy1295 commented on lab1/task_a.c
> +    if (symbol > 'Z'){
почему идёт сравнение с 'Z'?

2018-10-03 21:24 UTC, leshiy1295 commented on lab1/task_a.c
> +		return 0;
почему не выводится сообщение об ошибке?

2018-10-03 21:24 UTC, leshiy1295 commented on lab1/task_a.c
> +		return ERROR;
ERROR - это не bool

2018-10-05 13:36 UTC, leshiy1295 commented
Сообщения коммитов должны быть информативными!
И когда будете готовы к повторному ревью - напишите, пожалуйста, комментарий с runId.

2018-10-05 13:40 UTC, slevinsps commented
runId 1137

2018-10-07 14:14 UTC, leshiy1295 requested changes

2018-10-07 14:14 UTC, leshiy1295 commented on lab1/task_a.c
> +#include "stdio.h"
стандартные библиотеки нужно подключать через <>

2018-10-07 14:14 UTC, leshiy1295 commented on lab1/task_a.c
> +        answer += get_dec_digit_from_symbol(string[len_str - 1 - i]) * pow(base, i);
pow работает с double, а Вам нужен size_t

2018-10-07 14:14 UTC, leshiy1295 commented on lab1/task_a.c
> +        answer += get_dec_digit_from_symbol(string[len_str - 1 - i]) * pow(base, i);
https://rextester.com/l/c_online_compiler_clang - например, тут Ваша программа не компилируется

2018-10-07 15:24 UTC, slevinsps commented
runId 1353

2018-10-15 08:50 UTC, leshiy1295 commented
текущее изменение с double ничего не изменило - оно выполняется автоматически
ошибка была в возвращаемом значении - вам нужно было целочисленное значение, а возвращался double
в качестве решения можно было написать свою функцию, работающую с целыми числами (лучше) или явно преобразовать вывод в (size_t) (хуже)

2018-10-15 08:50 UTC, closed without merging